version: '3'

services:
  json-server:
    image: json-server
    build: ./json-server
    volumes:
      - ./json-server/data:/data
    ports:
      - 8080:80
  # ui:
  #   image: ui
  #   build: .
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 80:3000
