export const LOAD_VIEWS_SUCCESS = 'views.LOAD_VIEWS_SUCCESS';
export const UPDATE_CURRENT_VIEW = 'views.UPDATE_CURRENT_VIEW';

export const MENU_OPEN_CLOSE = 'views.MENU_OPEN_CLOSE';
export const UPDATE_SECTION = 'view.UPDATE_SECTION';